header = "/**\n * C bindings for saltyrtc-client crate.\n * https://github.com/saltyrtc/saltyrtc-client-ffi-rs\n **/"
include_guard = "saltyrtc_client_bindings_h"
language = "C"
braces = "SameLine"

[parse]
parse_deps = false

[fn]
args = "Vertical"