[package]
name = "saltyrtc-client"
version = "0.1.0"
authors = ["Danilo Bargen <danilo.bargen@threema.ch>"]

[dependencies]
log = "0.3"
websocket = "0.20.2"
native-tls = "0.1.4"
tokio-core = "0.1.9"
futures = "0.1.0"  # Make sure to use same version as websocket
error-chain = "0.11.0"
rmp-serde = "0.13"
rmpv = { version = "0.4", features = ["with-serde"] }
serde = "1.0"
serde_derive = "1.0"
rust_sodium = { version = "0.5.0", features = ["serde"] }
rust_sodium-sys = { version = "0.5.0" }
byteorder = "1.1"
data-encoding = "2.0.0-rc.2"
clippy = {version = "0.0.165", optional = true}

[dev-dependencies]
env_logger = "0.3"
clap = "2.27"

[features]
default = []
