[package]
name = "saltyrtc-client"
version = "0.1.0"
authors = ["Danilo Bargen <danilo.bargen@threema.ch>"]

[dependencies]
log = "0.3"
websocket = "0.20.2"
native-tls = "0.1.4"
tokio-core = "0.1.9"
futures = "0.1.0"
error-chain = "0.11.0"
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"
rust_sodium = { version = "0.5.0", features = ["serde"] }
byteorder = "1.1"

[dev-dependencies]
env_logger = "0.3"
