version: 2
jobs:
  build:
    docker:
      - image: rust:1.20
    steps:
      - checkout
      # Install apt dependencies
      - run: apt-get update && apt-get install -yq libsodium18 libsodium-dev
      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v5-cargo-cache-{{ .Branch }}
            - v5-cargo-cache
      - run: cargo build && cargo test
      - run: cargo install --force cargo-audit && cargo audit
      - save_cache:
          key: v5-cargo-cache-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v5-cargo-cache
          paths:
            - target
            - /usr/local/cargo
